### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/doc#1]
* [ ] css
* [ ] Solve the broken href. We need transform like `foo.md` or `foo.md#bar` to `foo` and `foo#bar`.
* [ ] Relocate href pointed back to Github Homebrew Repo to the document here.
* [ ] Fix missing text in http://brew.sh/doc/brew.1
